### ISSUE TITLE
vue3 not supports?

### ISSUE THREAD

**Issue by asterisk100** [credred/vue-drag-select#15]
vue3 not supports?

**Comment by credred** [comment]
> vue3 not supports?

No. I will support it as soon as possible.

**Comment by musiwei** [comment]
Hi credred, thanks for the great plugin, just following up on the Vue 3 support progress. Thank you.

**Comment by credred** [comment]
Sorry for the speed of progress too slow, I will support vue3 in the week.

**Comment by credred** [comment]
Hi @musiwei @asterisk100 , the repo has supported vue3. https://github.com/credred/vue-drag-select/releases

**Comment by asterisk100** [comment]
@credred GoodNews thanks
