### ISSUE TITLE
DragSelect.vue.d.ts has type undefined

### ISSUE THREAD

**Issue by eddie-englund** [credred/vue-drag-select#21]
Hi!

The generated Dragselect.vue.d.ts as the "modelValue" set to "undefined", but this should be "any" by checking the implementation it should be:

```ts
type modelValue<T> = undefined | T[] | Set<T>
```

or something similar. Currently have it always be undefined is making my build fail :/

**Comment by credred** [comment]
I'm sorry to see this problem so late, I will solve it as soon as possible

**Comment by credred** [comment]
This problem has been fixed in 2.0.4 version. Thank you for providing feedback on this issue

**Comment by eddie-englund** [comment]
Hi,

Thank you for solving this!
