### ISSUE TITLE
Are there plans to support mulitple selection with shift?

### ISSUE THREAD

**Issue by gray-adeyi** [credred/vue-drag-select#29]
While I'm able to click on a single element and also drag to select. Will there be support for shift and click to select multiple for cases where I want to select element 0, 9,15 from the storybook demo

**Comment by credred** [comment]
Yes, I plan to add this feature this week

**Comment by zkhabersang** [comment]
Hello, great library! Any updates on adding the shift + click feature in order to make multiple selections?
